type app-list-%COMPUTERNAME% | fzf ^
--delimiter "\|" ^
--ansi ^
--with-nth "1..-2" ^
--reverse ^
--info inline ^
--no-sort ^
--header-first ^
--header "SCOOPFZ: F1:Homepage | F2:Install | F3:Uninstall | ctrl-i:installed" ^
--preview-window "right:40:wrap" ^
--preview-label "HELP" ^
--preview "echo {2} & echo {4} & type help.txt" ^
--bind "ctrl-i:change-query(^*)" ^
--bind "home:first" ^
--bind "end:last" ^
--bind "F1:execute-silent(start """""" {-1})" ^
--bind "F2:execute(scoop install {2})" ^
--bind "F3:execute(scoop uninstall {2})"
